### ISSUE TITLE
11 out of 12 unit test caases failed for longest range solution

### ISSUE THREAD

**Issue by hayfin-kashifs** [subash774/hayfin#1]
https://www.algoexpert.io/questions/Largest%20Range. You can confirm from here.

**Comment by subash774** [comment]
Sorry, while porting over the question I forgot that I had to return the range of the number itself and not the array indices. Will fix that ASAP.

**Comment by subash774** [comment]
@hayfin-kashifs Code updated with the latest push. All test cases now pass. Sorry for the misunderstanding.
